# -*- coding: utf-8 -*-
"""HW2_hash_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gv5bDI3vtrou0dcq-0dZh_GCnYMBTsgH
"""

from google.colab import files

uploaded = files.upload()

import os

filename = "hw2_data.txt"
filepath = os.path.join("/content", filename)

import matplotlib.pyplot as plt
import os


def count_words_with_dict(filename):
    word_counts = {}

    with open(filename, 'r', encoding='utf-8') as file:
        for line in file:
            word = line.strip()
            if word:
                if word in word_counts:
                    word_counts[word] += 1
                else:
                    word_counts[word] = 1
    return word_counts


def plot_histogram(word_counts):
    sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)
    words, counts = zip(*sorted_words)

    plt.figure(figsize=(12, 6))
    plt.bar(words, counts, color='skyblue')
    plt.xlabel('Words')
    plt.ylabel('Frequency')
    plt.title('Word Frequency Histogram')
    plt.xticks(rotation=45, ha='right')
    plt.show()


filename = "/content/hw2_data.txt"


if os.path.exists(filename):
    word_counts = count_words_with_dict(filename)
    print(f"不重複的英文字數量: {len(word_counts)}")
    print("每個英文字出現次數:")
    for word, count in word_counts.items():
        print(f"{word}: {count}")

    plot_histogram(word_counts)